function(print_build_summary)
    message(STATUS "")
    message(STATUS "** pgModeler build details **")
    message(STATUS "  PREFIX        = ${PREFIX}")
    message(STATUS "  BINDIR        = ${BINDIR}")
    message(STATUS "  PRIVATEBINDIR = ${PRIVATEBINDIR}")
    message(STATUS "  PRIVATELIBDIR = ${PRIVATELIBDIR} ")
    message(STATUS "  PLUGINSDIR    = ${PLUGINSDIR}")
    message(STATUS "  SHAREDIR      = ${SHAREDIR}")
    message(STATUS "  CONFDIR       = ${CONFDIR}")
    message(STATUS "  DOCDIR        = ${DOCDIR}")
    message(STATUS "  LANGDIR       = ${LANGDIR}")
    message(STATUS "  SAMPLESDIR    = ${SAMPLESDIR}")
    message(STATUS "  SCHEMASDIR    = ${SCHEMASDIR}")
    message(STATUS "")
    message(STATUS "* To change a variable value run qmake again by setting the new desired value, e.g.:")
    message(STATUS "  > cmake -DPREFIX=/usr/local CMakeList.txt")
    message(STATUS "")
    message(STATUS "* To proceed with build process by running: ")
    message(STATUS "  >  make && make install ")
    message(STATUS "")
    message(STATUS "* C compiler: ${CMAKE_C_COMPILER}")
    message(STATUS "* C++ compiler: ${CMAKE_CXX_COMPILER}")
    message(STATUS "* PostgreSQL headers: ${PGSQL_INC}")
    message(STATUS "* PostgreSQL libraries: ${PGSQL_LIBS}")
    message(STATUS "* LibXml2 headers: ${XML2_INC}")
    message(STATUS "* LibXml2 libraries: ${XML2_LIBS}")
    message(STATUS "")
endfunction()
