function(print_build_summary)
    message(STATUS "")
    message(STATUS "** pgModeler build details **")
    message(STATUS "")
    message(STATUS "  PGM_PREFIX        = ${PGM_PREFIX}")
    message(STATUS "  PGM_BINDIR        = ${PGM_BINDIR}")
    message(STATUS "  PGM_PRIVATEBINDIR = ${PGM_PRIVATEBINDIR}")
    message(STATUS "  PGM_PRIVATELIBDIR = ${PGM_PRIVATELIBDIR} ")
    message(STATUS "  PGM_PLUGINSDIR    = ${PGM_PLUGINSDIR}")
    message(STATUS "  PGM_SHAREDIR      = ${PGM_SHAREDIR}")
    message(STATUS "  PGM_CONFDIR       = ${PGM_CONFDIR}")
    message(STATUS "  PGM_DOCDIR        = ${PGM_DOCDIR}")
    message(STATUS "  PGM_LANGDIR       = ${PGM_LANGDIR}")
    message(STATUS "  PGM_SAMPLESDIR    = ${PGM_SAMPLESDIR}")
    message(STATUS "  PGM_SCHEMASDIR    = ${PGM_SCHEMASDIR}")
    message(STATUS "")
    message(STATUS "* To change a variable value run qmake again by setting the new desired value, e.g.:")
    message(STATUS "  > cmake -DPREFIX=/usr/local CMakeList.txt")
    message(STATUS "")
    message(STATUS "* To proceed with build process by running: ")
    message(STATUS "  >  make && make install ")
    message(STATUS "")
    message(STATUS "* C compiler: ${CMAKE_C_COMPILER}")
    message(STATUS "* C++ compiler: ${CMAKE_CXX_COMPILER}")
    message(STATUS "* PostgreSQL headers: ${PGSQL_INC}")
    message(STATUS "* PostgreSQL libraries: ${PGSQL_LIBS}")
    message(STATUS "* LibXml2 headers: ${XML2_INC}")
    message(STATUS "* LibXml2 libraries: ${XML2_LIBS}")
    message(STATUS "")
endfunction()
