@set PGMODELER_ROOT=C:\pgmodeler
@set PGMODELER_CONF_DIR=%PGMODELER_ROOT%\conf
@set PGMODELER_SCHEMAS_DIR=%PGMODELER_ROOT%\schemas
@set PGMODELER_LANG_DIR=%PGMODELER_ROOT%\lang
@set PGMODELER_PLUGINS_DIR=%PGMODELER_ROOT%\plugins
@set PGMODELER_TMP_DIR=%PGMODELER_ROOT%\tmp
@set PGMODELER_LIB_DIR=%PGMODELER_ROOT%\lib
@set PATH=%PGMODELER_LIB_DIR%;%PATH%

%PGMODELER_ROOT%\pgmodeler.exe

