#/bin/bash
PGMODELER_ROOT=`pwd`
export PGMODELER_CONF_DIR=$PGMODELER_ROOT/conf
export PGMODELER_SCHEMAS_DIR=$PGMODELER_ROOT/schemas
export PGMODELER_LANG_DIR=$PGMODELER_ROOT/lang
export PGMODELER_TMP_DIR=$PGMODELER_ROOT/tmp
export PGMODELER_PLUGINS_DIR=$PGMODELER_ROOT/plugins
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$PGMODELER_ROOT/lib

open "$PGMODELER_ROOT/pgmodeler.app"
