set PGMODELER_ROOT="C:\Users\raphael\Desktop\pgmodeler-code\build"
set PGMODELER_CONFIGS_DIR=%PGMODELER_ROOT%\conf
set PGMODELER_SCHEMAS_DIR=%PGMODELER_ROOT%\schemas
set PGMODELER_LANG_DIR=%PGMODELER_ROOT%\lang
set PGMODELER_PLUGINS_DIR=%PGMODELER_ROOT%\plugins

%PGMODELER_ROOT%\pgmodeler.exe
