include(../pgmodeler.pro)

TEMPLATE = app
TARGET = test
DESTDIR = ../build

LIBS += $$DESTDIR/$$LIBUTILS \
	$$DESTDIR/$$LIBPARSERS \
	$$DESTDIR/$$LIBPGCONNECTOR \
	$$DESTDIR/$$LIBOBJRENDERER \
	$$DESTDIR/$$LIBPGMODELER \
	$$DESTDIR/$$LIBPGMODELERUI

SOURCES += $$PWD/src/main.cpp
