# Template code for data dictionary generation
# CAUTION: Do not modify this file unless you know what you are doing.
#          Code generation can be broken if incorrect changes are made. 

<html> $br
<head> $br
[	<meta charset="utf-8"> 
	<title>Data dictionary generated by pgModeler</title>] $br

%if {splitted} %then
	 [	<link rel="stylesheet" type="text/css" href="styles.css">] $br
%else
	[	<style>] $br
		{styles} $br 
	[	</style>] $br
%end

</head>
<body> $br

[<h3 id="index"> Data dictionary of DB_NAME</h3>]
<ul>
	<li><a $sp href="\#public.table_test">public.table_test</a></li>
	<li><a $sp href="\#public.table_test1">public.table_test1</a></li>
</ul>

{objects}

</body> $br
</html> $br
