# Template code for data dictionary generation
# CAUTION: Do not modify this file unless you know what you are doing.
#          Code generation can be broken if incorrect changes are made. 

%if {splitted} %then
[<html>
<head>
	<meta charset="utf-8"> 
	<title>Data dictionary generated by pgModeler</title>
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>]
%end

$br [<h3> Data dictionary of ] {name} </h3>
$br [	] <ul $sp id="index">
$br [		] <li><strong>Tables</strong>
$br [			] <ul>
{items}
$br [			] </ul>
$br [		] </li>
$br [	] </ul>
$br

%if {splitted} %then
</body> $br
</html>
%end
