# Basic structure for the diff script file generated by diff process
# PostgreSQL Version: 9.x
# CAUTION: Do not modify this file unless you know what you are doing.
#          Code generation can be broken if incorrect changes are made.

[-- Database diff generated with pgModeler (PostgreSQL Database Modeler).] $br
[-- pgModeler  version: ] @{pgmodeler-ver} $br
[-- PostgreSQL version: ] @{pgsql-ver} $br

$br
[-- ] $ob Diff $sp summary $cb $br
[-- Dropped objects: ] @{drop} $br
[-- Created objects: ] @{create} $br
[-- Changed objects: ] @{change} $br

$br
[SET check_function_bodies = false;] $br
[-- ddl-end --] $br

%if @{drop-cmds} %then
  $br
  [-- Dropped objects -- ] $br
  @{drop-cmds}
  [-- ddl-end --] $br
%end

%if @{create-cmds} %then
  $br
  [-- Created objects -- ] $br
  @{create-cmds}
  [-- ddl-end --] $br
%end

%if @{alter-cmds} %then
  $br
  [-- Changed objects -- ] $br
  @{alter-cmds}
  [-- ddl-end --] $br
%end
