# Template code for data dictionary generation
# CAUTION: Do not modify this file unless you know what you are doing.
# Code generation can be broken if incorrect changes are made.

%if %not {split} %and {datadictidx} %then
	\#\#\s [Data dictionary generated by pgModeler] \n

	{datadictidx}

	\n --- \n
%end

{objects}

@include "footer"
