# Template code for data dictionary generation
# CAUTION: Do not modify this file unless you know what you are doing.
# Code generation can be broken if incorrect changes are made.

\#\#\s [Data dictionary generated by pgModeler] \n

%if %not {split} %and {datadictidx} %then
	{datadictidx}
%end

\n --- \n

{objects}

\n [Generated at ] _{date}_ [ by **pgModeler ] {version} ** \n
\[ [PostgreSQL Database Modeler - pgmodeler.io ] \] (https://pgmodeler.io) \n
[Copyright © 2006 - ] {year} [ Raphael Araújo e Silva ] \n