# Template code for data dictionary generation
# CAUTION: Do not modify this file unless you know what you are doing.
# Code generation can be broken if incorrect changes are made.

\n [<a name="index"></a>] \n
\#\#\#\s [Database: ] {name} \n\n

%if {table} %then
 	\#\#\#\s Tables \n 	
 	{table}
%end

\n

# %if {foreigntable} %then
# 	{spc} <li><br/><strong>[Foreign tables]</strong>
# 	{spc} <ul>
# 	{foreigntable}
# 	{spc} </ul>
# 	{spc} </li>
# %end

# %if {view} %then
# 	{spc} <li><br/><strong>Views</strong>
# 	{spc} <ul>
# 	{view}
# 	{spc} </ul>
# 	{spc} </li>
# %end

# {spc} </ul>
# \n

# %if {split} %then

# 	[<footer>
# 	Generated by <a href="https://pgmodeler.io"> PostgreSQL Database Modeler - pgModeler</a><br/>
# 	Copyright © 2006 - ] {year} [ Raphael Araújo e Silva
# 	</footer> ]

# 	</body> \n
# 	</html>
# %end
