# Template code for data dictionary generation
# CAUTION: Do not modify this file unless you know what you are doing.
# Code generation can be broken if incorrect changes are made.

<html> \n
<head> \n
[ <meta charset="utf-8">
<title>Data dictionary generated by pgModeler</title> ] \n

%if {split} %then
	[ <link rel="stylesheet" type="text/css" href="styles.css"> ] \n
%else
	[ <style> ] \n
	{styles} \n
	[ </style> ] \n
%end

</head> \n
<body> \n

%if %not {split} %and {datadictidx} %then
	{datadictidx}
%end

{objects}

[ <footer>
Generated at <em> ] {date} [ </em> by <strong>pgModeler ] {version} [ </strong><br/>
<a href="https://pgmodeler.io">PostgreSQL Database Modeler - https://pgmodeler.io</a><br/>
Copyright © 2006 - ] {year} [ Raphael Araújo e Silva
</footer> ]

</body> \n
</html> \n
