# Template code for data dictionary generation
# CAUTION: Do not modify this file unless you know what you are doing.
# Code generation can be broken if incorrect changes are made.

<html> \n
<head> \n
[ <meta charset="utf-8">
<title>Data dictionary generated by pgModeler</title> ] \n

%if {split} %then
	[ <link rel="stylesheet" type="text/css" href="styles.css"> ] \n
%else
	[ <style> ] \n
	{styles} \n
	[ </style> ] \n
%end

</head> \n
<body> \n